In [1]:
!pip install numpy


You should consider upgrading via the 'C:\Users\Subhajit ghosh\python.exe -m pip install --upgrade pip' command.


In [1]:
import numpy as np


In [5]:
l = [1 , 3 , 4 , 5]
a = np.array(l)
b = np.array([1 , 2 , 3 ,4])
print(a , type(a))
print(b , type(b))

[1 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4] <class 'numpy.ndarray'>


In [2]:
l4 = [1 , 2 , 3 ,4 ,5 ,6 ,7 ,8 ,9]
a = np.array(l4)
print(l4)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
a.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(a + b)
print(a * b)
print(a - b)
print(a**2)

[2 5 7 9]
[ 1  6 12 20]
[0 1 1 1]
[ 1  9 16 25]


In [11]:
l2 = [[1 , 2 ,3 ],[3 , 5 ,6]]
a = np.array(l2)
print(a , type(a))

[[1 2 3]
 [3 5 6]] <class 'numpy.ndarray'>


In [12]:
print(a.shape)

(2, 3)


In [13]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [15]:
a.ndim

2

In [16]:
b = np.array([1 , 2 , 3 , 4][1 , 5 , 6 , 7])
print(b)

[1 2 3 4]


In [18]:
print(b.shape , b.ndim)

(4,) 1


In [19]:
b.reshape(1 , 4)
print(b , b.ndim)

[1 2 3 4] 1


In [20]:
a = np.ones((2 , 4 , 5))
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [21]:
a.sum(0)

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [23]:
a = np.ones((2 , 4 , 5))
print(a)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [24]:
a.sum(2)

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [25]:
a = np.arange(1,51).reshape(2 , 5 ,-1)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


## Array Creation and attributes
creating array from a sequence: 1d, 2d
arithmetic operations on np array
num of dim, shape, size, dtype, itemsize

In [2]:
import numpy as np

In [3]:
l = [1 , 2 , 3 ,4]
a = np.array(l)
b = np.array([7 , 8 , 9 , 10])

In [4]:
print(a , b)

[1 2 3 4] [ 7  8  9 10]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(type(a[0]))

<class 'numpy.int32'>


In [7]:
print(a+b)

[ 8 10 12 14]


In [11]:
l2 = [[2 , 4 ,5 ,6] , [5 , 1, 4 ,5]]

In [37]:
a = np.array(l2)
print(a)

[[2 4 5 6]
 [5 1 4 5]]


In [38]:
print(a.shape)
print(a.itemsize)

(2, 4)
4


In [16]:
print(a.ndim)

2


In [18]:
l3 = [1 , 4 ,5 ,6]
a = np.array(l3)
print(a , a.ndim)

[1 4 5 6] 1


In [20]:
print(a.shape , a.ndim)

(4,) 1


In [22]:
l4 = [[2 , 4 ,5 ,6],[6 , 4, 6 ,3]]
a = np.array(l4)
a.shape

(2, 4)

In [23]:
a.reshape(8 , 1)

array([[2],
       [4],
       [5],
       [6],
       [6],
       [4],
       [6],
       [3]])

In [24]:
a.reshape(4 , 2)

array([[2, 4],
       [5, 6],
       [6, 4],
       [6, 3]])

In [25]:
print(a)

[[2 4 5 6]
 [6 4 6 3]]


In [31]:
print(type(a[0]))

<class 'numpy.ndarray'>


In [32]:
print(type(a[0][1]))

<class 'numpy.int32'>


In [34]:
b = np.float32

In [35]:
type(b)

type

In [36]:
a.itemsize

4

## creating fixed size array
- zeroes 
- one
-empty

In [40]:
a = np.ones((2,5) , dtype = np.int32)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [43]:
type(a)

numpy.ndarray

In [48]:
print(a.dtype)

int32


In [51]:
b = np.zeros((3,4) , dtype = np.float32)
print(b)
print(b.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float32


In [52]:
c = np.zeros((2 , 5 ,6) , dtype = np.int32)
print(c)
print(c.dtype)

[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]
int32


In [53]:
d = np.empty((5 , 6))
print(c)

[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]


## Creating sequences of numbers
 - arange
- linspace

In [59]:
a = np.arange?


In [61]:
a = np.arange(100 , 1 , -1)
print(a)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2]


In [62]:
b = np.arange(50 , 4 , -2)
b

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6])

In [67]:
c = np.arange(100 , 4 ,-1).reshape(3 , 2  , -1)
print(c)

[[[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85]
  [ 84  83  82  81  80  79  78  77  76  75  74  73  72  71  70  69]]

 [[ 68  67  66  65  64  63  62  61  60  59  58  57  56  55  54  53]
  [ 52  51  50  49  48  47  46  45  44  43  42  41  40  39  38  37]]

 [[ 36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21]
  [ 20  19  18  17  16  15  14  13  12  11  10   9   8   7   6   5]]]


In [70]:
d = np.arange(1 , 21 , 1)
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [74]:
d.reshape(4 , -1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [76]:
a = np.arange(8).reshape(2,-1)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [78]:
b = np.linspace?

In [ ]:
b = np.linspace

In [79]:
a = np.linspace(2,50, 100)
print(a)

[ 2.          2.48484848  2.96969697  3.45454545  3.93939394  4.42424242
  4.90909091  5.39393939  5.87878788  6.36363636  6.84848485  7.33333333
  7.81818182  8.3030303   8.78787879  9.27272727  9.75757576 10.24242424
 10.72727273 11.21212121 11.6969697  12.18181818 12.66666667 13.15151515
 13.63636364 14.12121212 14.60606061 15.09090909 15.57575758 16.06060606
 16.54545455 17.03030303 17.51515152 18.         18.48484848 18.96969697
 19.45454545 19.93939394 20.42424242 20.90909091 21.39393939 21.87878788
 22.36363636 22.84848485 23.33333333 23.81818182 24.3030303  24.78787879
 25.27272727 25.75757576 26.24242424 26.72727273 27.21212121 27.6969697
 28.18181818 28.66666667 29.15151515 29.63636364 30.12121212 30.60606061
 31.09090909 31.57575758 32.06060606 32.54545455 33.03030303 33.51515152
 34.         34.48484848 34.96969697 35.45454545 35.93939394 36.42424242
 36.90909091 37.39393939 37.87878788 38.36363636 38.84848485 39.33333333
 39.81818182 40.3030303  40.78787879 41.27272727 41.

In [81]:
(50 - 2 )/ 99

0.48484848484848486

In [82]:
b = np.linspace(-50 , -2 , 100)
print(b)

[-50.         -49.51515152 -49.03030303 -48.54545455 -48.06060606
 -47.57575758 -47.09090909 -46.60606061 -46.12121212 -45.63636364
 -45.15151515 -44.66666667 -44.18181818 -43.6969697  -43.21212121
 -42.72727273 -42.24242424 -41.75757576 -41.27272727 -40.78787879
 -40.3030303  -39.81818182 -39.33333333 -38.84848485 -38.36363636
 -37.87878788 -37.39393939 -36.90909091 -36.42424242 -35.93939394
 -35.45454545 -34.96969697 -34.48484848 -34.         -33.51515152
 -33.03030303 -32.54545455 -32.06060606 -31.57575758 -31.09090909
 -30.60606061 -30.12121212 -29.63636364 -29.15151515 -28.66666667
 -28.18181818 -27.6969697  -27.21212121 -26.72727273 -26.24242424
 -25.75757576 -25.27272727 -24.78787879 -24.3030303  -23.81818182
 -23.33333333 -22.84848485 -22.36363636 -21.87878788 -21.39393939
 -20.90909091 -20.42424242 -19.93939394 -19.45454545 -18.96969697
 -18.48484848 -18.         -17.51515152 -17.03030303 -16.54545455
 -16.06060606 -15.57575758 -15.09090909 -14.60606061 -14.12121212
 -13.63636

In [86]:
(-2 + 50) / 99

0.48484848484848486

In [87]:
49.51515152 - 50


-0.4848484799999966

## Basic Operations
- element-wise arithmatic and comparison operation with scaler and arrays
- matrix multiplication
- +=, -=, *= etc. changes value inplace
- Resulting matrix has a more general/ precise dtype

In [22]:
a = np.arange(3, 21)
print(a)
a < 10

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False])

In [12]:
b = np.linspace(3,20,20)
print(b)
b < 10

[ 3.          3.89473684  4.78947368  5.68421053  6.57894737  7.47368421
  8.36842105  9.26315789 10.15789474 11.05263158 11.94736842 12.84210526
 13.73684211 14.63157895 15.52631579 16.42105263 17.31578947 18.21052632
 19.10526316 20.        ]


array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [29]:
a = np.arange(1, 21)
print(a)
a < 10

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [30]:
c = np.arange(11,31)
print(c)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [23]:
c*a

array([  3,   8,  15,  24,  35,  48,  63,  80,  99, 120, 143, 168, 195,
       224, 255, 288, 323, 360])

In [31]:
a = a.reshape(4,5)
b = b.reshape(5,4)
a@b

array([[ 188.15789474,  201.57894737,  215.        ,  228.42105263],
       [ 442.10526316,  477.89473684,  513.68421053,  549.47368421],
       [ 696.05263158,  754.21052632,  812.36842105,  870.52631579],
       [ 950.        , 1030.52631579, 1111.05263158, 1191.57894737]])

In [32]:
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [39]:
a += 1
print(a)

[[ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]
 [22 23 24 25 26]]


## Unary Operations
- sum , min , max

In [6]:
a = np.arange(1 , 10 , dtype = np.int32 ).reshape(3,-1)
b = np.arange(1 , 10 , dtype = np.int64).reshape(3,-1)
print(a , b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(a , "\n" , b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np.sum?

In [10]:
np.sum(a)

45

In [11]:
np.sum(a , axis = 0)

array([12, 15, 18])

In [12]:
np.sum(a , axis = 1)

array([ 6, 15, 24])

In [13]:
a.max()

9

In [14]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
a.max(0)

array([7, 8, 9])

In [16]:
a.min(0)

array([1, 2, 3])

In [22]:
c = np.ones((2 , 4,5) , dtype = np.int32)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [24]:
c.sum(0)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [25]:
c.sum(1)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

## Array indexing, slicing
- similar to list slicing
- slice is considered complete for missing slices, when fewer indices provided

In [29]:
a = np.arange(1,21).reshape(4,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [30]:
 a = np.arange(1,51).reshape(2,5,-1)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]


In [31]:
a[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [32]:
a[1]

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [33]:
a[1 ,3:]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

## Stacking of arrays
- hstack , vstack , concatenate

In [34]:
a = np.arange(1 , 7).reshape(2,3)
b = np.arange(0,6).reshape(2,3)
print(a , "\n" , b)

[[1 2 3]
 [4 5 6]] 
 [[0 1 2]
 [3 4 5]]


In [35]:
np.hstack?

In [36]:
np.hstack([a,b])

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5]])

In [37]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 5]])

In [38]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
b.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [40]:
a , b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [41]:
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 5]])

In [42]:
np.concatenate([a,b] , axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 2],
       [3, 4, 5]])

In [43]:
np.concatenate([a,b] , axis=1)

array([[1, 2, 3, 0, 1, 2],
       [4, 5, 6, 3, 4, 5]])

### Making copies
- shallow copy
- deep copy

In [46]:
a = np.arange(1,7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [47]:
b = a         # we created a shallow copy of a , we haven't create new array assignment
b[0] = 2
print(b)

[[2 2 2]
 [4 5 6]]


In [48]:
print(a)

[[2 2 2]
 [4 5 6]]


In [49]:
a

array([[2, 2, 2],
       [4, 5, 6]])

In [50]:
c = a[1]

In [51]:
c

array([4, 5, 6])

In [53]:
c[1:] = 0
c

array([4, 0, 0])

In [54]:
a

array([[2, 2, 2],
       [4, 0, 0]])

In [57]:
t = np.arange(3,9).reshape(2,3)
t

array([[3, 4, 5],
       [6, 7, 8]])

In [66]:
t[1 , :2 ] = 4
t

array([[3, 4, 5],
       [4, 4, 5]])

In [70]:
t[1 , 2:] = 9
t

array([[3, 4, 5],
       [6, 8, 9]])

In [71]:
p = a.copy()  # deep copy

In [73]:
print(a , "\n" , p)

[[2 2 2]
 [4 0 0]] 
 [[2 2 2]
 [4 0 0]]


In [79]:
p[1] = 3

In [80]:
print(a , "\n" , p)


[[2 2 2]
 [3 3 3]] 
 [[2 2 2]
 [3 3 3]]


## Array indexing through integer and boolean arrays

In [4]:
a = np.arange(1,101).reshape(20,-1)
print(a)
print(a.shape)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]
 [ 26  27  28  29  30]
 [ 31  32  33  34  35]
 [ 36  37  38  39  40]
 [ 41  42  43  44  45]
 [ 46  47  48  49  50]
 [ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]
(20, 5)


In [5]:
idx = [1 , 4 ,5, 9] # integer based indexing , array subsetting
a[idx]

array([[ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [46, 47, 48, 49, 50]])

In [6]:
rt = [8 , 9]
a[rt]

array([[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [14]:
a[:,0]

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [52]:
a

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [55]:
a[:,1]>51

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [17]:
boolean_idx = a[:,0]>40
print(boolean_idx , boolean_idx.shape)

[False False False False False False False False  True  True  True  True
  True  True  True  True  True  True  True  True] (20,)


In [18]:
a[boolean_idx]  # boolean array based subsetting

array([[ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

### Generate data

In [22]:
a[: , 1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23],
       [27, 28],
       [32, 33],
       [37, 38],
       [42, 43],
       [47, 48],
       [52, 53],
       [57, 58],
       [62, 63],
       [67, 68],
       [72, 73],
       [77, 78],
       [82, 83],
       [87, 88],
       [92, 93],
       [97, 98]])

In [41]:
p = a[: , 2:4] 
print(p)

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]
 [28 29]
 [33 34]
 [38 39]
 [43 44]
 [48 49]
 [53 54]
 [58 59]
 [63 64]
 [68 69]
 [73 74]
 [78 79]
 [83 84]
 [88 89]
 [93 94]
 [98 99]]


In [42]:
bool_idx = a[:,2] >  60
print(bool_idx)

[False False False False False False False False False False False False
  True  True  True  True  True  True  True  True]


In [43]:
a[bool_idx, 2:4]

array([[63, 64],
       [68, 69],
       [73, 74],
       [78, 79],
       [83, 84],
       [88, 89],
       [93, 94],
       [98, 99]])

In [46]:
a[bool_idx , 2:]

array([[ 63,  64,  65],
       [ 68,  69,  70],
       [ 73,  74,  75],
       [ 78,  79,  80],
       [ 83,  84,  85],
       [ 88,  89,  90],
       [ 93,  94,  95],
       [ 98,  99, 100]])

## generate data 

In [50]:
np.random.randint(1 , 8)    # generate random value

5

In [51]:
np.random.randint(1 , 8 , 4)

array([4, 5, 1, 2])

## shuffle data

In [59]:
idx = np.arange(0, 21)
print(idx)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [60]:
np.random.shuffle(idx)
print(idx)

[11 10 16 12 19  5 18  6  9  2  1  4 13  8 17 20 14 15  3  0  7]


In [61]:
a

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])